# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoApp', '0002_auto_20170513_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='mark',
            new_name='mark_id',
        ),
    ]
